### ISSUE TITLE
Error in project setup : blocked on "creating files" (W10)

### ISSUE THREAD

**Issue by EdwardBunzl** [googledatastudio/tooling#46]
Hello,

I'm trying to setup local devlopment environment as explained on https://developers.google.com/datastudio/visualization/local-dev.

The execution of dscc-gen viz seems to block on "creating directories and copying template files..."
![Capture](https://user-images.githubusercontent.com/54099255/63005925-bf3ac500-be7d-11e9-9221-08e1bdae108b.PNG)

When i look in windows explore, it seems that files have been correctly created
![Capture2](https://user-images.githubusercontent.com/54099255/63005948-cbbf1d80-be7d-11e9-8d8b-fbcfda1846c2.PNG)

Here is the output of npx @google/dscc-gen -v
![Capture3](https://user-images.githubusercontent.com/54099255/63005987-e0031a80-be7d-11e9-879d-ede8dc0678ff.PNG)

OS : windows 10

Do you know why this is happening ?

Kind regards,

Edward

**Comment by y3l2n** [comment]
I just deployed a new version that *should* be windows compatible; can you try again?

**Comment by y3l2n** [comment]
Fixed by https://github.com/googledatastudio/tooling/pull/100
