### ISSUE TITLE
Viz creation fails without useful error message at bucket input step if bucket has "Bucket Policy Only"

### ISSUE THREAD

**Issue by minhaz** [googledatastudio/tooling#52]
Error msg:
```
? Project name myvizpack
? What is your dev bucket? gs://
>> TypeError: util.getSystemErrorName is not a function
```

**Comment by diminishedprime** [comment]
Hi, could you run `node --version` and post the results? It looks like `util.getSystemErrorName` is a node function that was only backported to node >=8.12.0.

**Comment by minhaz** [comment]
v9.5.0

**Comment by minhaz** [comment]
This seems to WAI for node v10.15.3 but we get the above error message for node v9.5.0.

Recommend updating node to get better error messages

**Comment by erickoledadevrel** [comment]
Just ran into this problem as well. If a minimum version of Node is required it should be specified in the package.json file:

https://docs.npmjs.com/files/package.json#engines

Please reopen this issue to track this.

**Comment by erickoledadevrel** [comment]
Even when upgrading to a node version that supports that method, the original problem also remains: the generation fails if the bucket has a "uniform bucket-level access" policy. A fine-grained permissions policy isn't listed as a requirement in the docs, so the script should be updated to handle this case.
